#name: Latest Blogs from Medium
#on:
#  schedule:
    # Runs every hour
#    - cron: '0 * * * *'
#  workflow_dispatch:

# jobs:
  # update-readme-with-medium:
   #  name: Update this repo's README with latest blogs from Aritra Ghosh Medium
  #   runs-on: ubuntu-latest
  #   steps:
    #   - uses: actions/checkout@v2
  #     - uses: gautamkrishnar/blog-post-workflow@master
 #        with:
#           comment_tag_name: "BLOG-CONTENT-LIST"
 #          feed_list: "https://the-clever-idiot.medium.com/"
